# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys
from PyQt5.QtWidgets import QApplication, QMainWindow

from PyQt5 import QtCore, QtGui, QtWidgets

import test2

def clicked(Item):
    print(Item)
    Item.listWidget().insertItem(3,"hahaha")

def buttonClicked(button):
    print(button)
    subWindow = QMainWindow()
    subUI = test2.Ui_MainWindow()
    subUI.setupUi(subWindow)
    subWindow.show()

